import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
    parent: {
        flex: 1,
        width: '100%',
        height: '100%',
        backgroundColor: '#fff',
        flexDirection: 'column',
    },
    pagecontent: {
        flex: 4,
        flexDirection: 'column',
        width: '100%',
        height: '100%',
        paddingTop: 5,
        paddingBottom: 5,
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#fff',
    },
    parentmain: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        flexDirection: 'column',
        marginTop: 100,
        padding: 20,
    },
    inputfieldregular: {
        height: 50,
        width: '100%',
        borderBottomWidth: 1,
        borderBottomColor: '#4285F4',
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 20,
        marginTop: 50,
        fontWeight: '400',
        fontSize: 14,
        textAlign: 'left',
        color: '#000',
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' : 'Roboto-Medium',
    },
    inputfieldpassword: {
        height: 50,
        width: '100%',
        borderBottomWidth: 1,
        borderBottomColor: '#4285F4',
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 20,
        fontWeight: '400',
        fontSize: 14,
        textAlign: 'left',
        color: '#000',
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' : 'Roboto-Medium',
    },
    cardcontainerbasic: {
        width: '100%',
        height: 50,
        borderRadius: 10,
        backgroundColor: '#4285F4',
        marginLeft: 10,
        marginRight: 10,
        marginTop: 20,
        shadowColor: '#4285F4',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        ...Platform.select({
            ios: {
                shadowRadius: 1,
                elevation: 2,
            },
            android: {
                shadowRadius: 2,
                elevation: 4,
            },
        }),
    },
    cardlogininner: {
        flex: 1,
        width: '100%',
        height: '100%',
        justifyContent: 'center',
    },
    loginbutton: {
        flex: 1,
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    passwordshowiconparent: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewparentpassword: {
        flex: 1,
        width: '95%',
        height: '95%',
        flexDirection: 'row',
        justifyContent: 'center',
        marginLeft: 5,
        marginRight: 5,
    },
    textsignin: {
        marginTop: 20,
        lineHeight: 20,
        textAlign: 'right',
        fontSize: 14,
        color: '#4285F4',
        fontWeight: '600',
        padding: 2,
        width: '100%',
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' : 'Roboto-Medium',
    },
});