import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
    parent: {
        flex: 1,
        width: '100%',
        height: '100%',
        backgroundColor: '#4285F4',
        flexDirection: 'column',
    },
    pagecontent: {
        flex: 4,
        flexDirection: 'column',
        width: '100%',
        height: '100%',
        paddingTop: 200,
        paddingBottom: 5,
        paddingLeft: 10,
        paddingRight: 10,
        backgroundColor: '#fff',
    },
    parentmain: {
        flex: 1,
        width: '100%',
        alignItems: 'center',
        flexDirection: 'column',
        marginTop: 20,
        padding: 20,
    },
    inputfieldregular: {
        height: 50,
        width: '100%',
        borderBottomWidth: 1,
        borderBottomColor: '#4285F4',
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 20,
        fontWeight: '400',
        fontSize: 14,
        textAlign: 'left',
        color: '#000',
        fontFamily: Platform.OS === 'ios' ? 'Helvetica' : 'Roboto-Medium',
    },
    cardcontainerbasic: {
        width: '100%',
        height: 50,
        borderRadius: 10,
        backgroundColor: '#4285F4',
        marginLeft: 10,
        marginRight: 10,
        marginTop: 20,
        shadowColor: '#4285F4',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        ...Platform.select({
            ios: {
                shadowRadius: 1,
                elevation: 2,
            },
            android: {
                shadowRadius: 2,
                elevation: 4,
            },
        }),
    },
    cardlogininner: {
        flex: 1,
        width: '100%',
        height: '100%',
        justifyContent: 'center',
    },
    loginbutton: {
        flex: 1,
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    parentinputfield: {
        flex: 5, 
        width: '100%', 
        height: '100%', 
        padding: 5,
        justifyContent: 'flex-end',
    },
    parentbuttons: {
        flex: 5, 
        width: '100%', 
        height: '100%', 
        padding: 5, 
        flexDirection: 'row',
        justifyContent: 'flex-start',
    },
    buttoninnerlayout: {
        flex: 2, 
        width: '100%', 
        height: '100%', 
        padding: 5, 
        alignItems: 'center',
    }
  });